// generated by build.rs, do not edit
//

use aisp_packet_macros::packet_register;

use crate::deserializer;
use crate::error::ParseError;
use crate::serializer;

pub trait Packet {
    const ID: u16;
}

pub mod adventure;
pub mod ai;
pub mod areasv;
pub mod auth;
pub mod avatar;
pub mod channel;
pub mod circle;
pub mod enquete;
pub mod friend;
pub mod heroine;
pub mod item;
pub mod mail;
pub mod mascot;
pub mod misc;
pub mod msg;
pub mod myprofile;
pub mod myroom;
pub mod npc;
pub mod ping;
pub mod quest;
pub mod robo;
pub mod version;
pub mod world;

packet_register! {
    adventure::AdventureUploadRateGetRequest,
    adventure::AdventureUploadRateGetResponse,
    ai::AiDownloadListGetRequest,
    ai::AiDownloadListGetResponse,
    ai::AiUploadRateGetRequest,
    ai::AiUploadRateGetResponse,
    areasv::AreasvEnterRequest,
    areasv::AreasvEnterResponse,
    areasv::AreasvLeaveRequest,
    areasv::AreasvLeaveResponse,
    auth::AuthenticateRequest,
    auth::AuthenticateResponseDevelop,
    auth::AuthenticateResponseFalure,
    auth::NotifyLogout,
    avatar::AvatarCreateRequest,
    avatar::AvatarCreateResponse,
    avatar::AvatarDataResponse,
    avatar::AvatarDestroyRequest,
    avatar::AvatarGetCreateInfoRequest,
    avatar::AvatarGetCreateInfoResponse,
    avatar::AvatarGetDataRequest,
    avatar::AvatarGetDataResponse,
    avatar::AvatarMove,
    avatar::AvatarNotifyData,
    avatar::AvatarSelectRequest,
    avatar::AvatarSelectResponse,
    channel::ChannelCheckResponse,
    channel::ChannelListGetMapRequest,
    channel::ChannelListGetRequest,
    channel::ChannelListGetResponse,
    channel::ChannelSelectRequest,
    channel::ChannelSelectResponse,
    circle::CircleChangeCoreAuthorityRequest,
    circle::CircleChangeCoreAuthorityResponse,
    circle::CircleChatInRequest,
    circle::CircleChatInResponse,
    circle::CircleChatOutRequest,
    circle::CircleChatPostRequest,
    circle::CircleChatPostResponse,
    circle::CircleCreateRequest,
    circle::CircleGetDataRequest,
    circle::CircleGetDataResponse,
    circle::CircleLeaderChangeResponse,
    circle::CircleMarkChangeRequest,
    circle::CircleMarkChangeResponse,
    circle::CircleMemberJoinAnswerRequest,
    circle::CircleMemberJoinMemberCancelRequest,
    circle::CircleMemberJoinMemberRequest,
    circle::CircleMemberJoinMemberResponse,
    circle::CircleMemberKickRequest,
    circle::CircleMessageChangeRequest,
    circle::CircleNotiftyChatOut,
    circle::CircleNotifyChatIn,
    circle::CircleNotifyJoinRequest,
    circle::CircleNotifyJoinRequestResult,
    circle::CircleNotifyMember,
    circle::CircleResignRequest,
    enquete::EnqueteAnswerRequest,
    enquete::EnqueteAnswerResponse,
    enquete::EnqueteGetRequest,
    enquete::EnqueteGetResponse,
    friend::FriendGetListDataRequest,
    friend::FriendGetListDataResponse,
    friend::FriendLinkTagGetFreeRequest,
    friend::FriendLinkTagGetRequest,
    friend::FriendLinkTagGetResponse,
    heroine::HeroineGetTicketBaseRequest,
    heroine::HeroineGetTicketBaseResponse,
    item::EmotionGetBaseListRequest,
    item::EmotionGetBaseListResponse,
    item::EmotionGetObtainedListRequest,
    item::EmotionGetObtainedListResponse,
    item::EquipOrderListRequest,
    item::EquipOrderListResponse,
    item::FurnitureGetBaseListRequest,
    item::FurnitureGetBaseListResponse,
    item::ItemEquipStartRequest,
    item::ItemEquipStartResponse,
    item::ItemGetBaseListRequest,
    item::ItemGetBaseListResponse,
    item::ItemGetListRequest,
    item::ItemGetListResponse,
    item::MapDataEnterEndRequest,
    item::MapDataEnterEndResponse,
    item::MissionDataRequest,
    item::MissionDataResponse,
    item::NiconiCommonsBaseListRequest,
    item::NiconiCommonsBaseListResponse,
    item::UccAdvFigureBaseListRequest,
    item::UccAdvFigureBaseListResponse,
    item::UccVoiceBaseListRequest,
    item::UccVoiceBaseListResponse,
    mail::MailBoxGetDataRequest,
    mail::MailBoxGetDataResponse,
    mail::MailDeleteRequest,
    mail::MailDeleteResponse,
    mail::MailOpenRequest,
    mail::MailOpenResponse,
    mail::MailPostRequest,
    mail::MailProtectCancelRequest,
    mail::MailProtectRequest,
    mail::MailProtectResponse,
    mascot::MascotGetCountRequest,
    mascot::MascotGetCountResponse,
    misc::MoneyDataGetRequest,
    misc::MoneyDataGetResponse,
    misc::MoneyNpsPointsRequest,
    misc::MoneyNpsPointsResponse,
    misc::TimeZoneGetRequest,
    misc::TimeZoneGetResponse,
    misc::UpdateOptionRequest,
    misc::UpdateOptionResponse,
    msg::CmdExecRequest,
    msg::LiveContestNotifyCommentDelete,
    msg::LiveContestNotifyCommentForward,
    msg::LoginRequest,
    msg::LoginResponse,
    msg::LogoutRequest,
    msg::LogoutResponse,
    msg::PlackardGetCommentLogRequest,
    msg::PostTalkRequest,
    myprofile::MyProfileAvatarEditRequest,
    myprofile::MyProfileAvatarEditResponse,
    myprofile::MyProfileAvatarGetRequest,
    myprofile::MyProfileCloseRequest,
    myroom::MyRoomGetFurnitureRequest,
    myroom::MyRoomGetFurnitureResponse,
    myroom::MyRoomNotifyFurnitue,
    npc::NpcGetDataRequest,
    npc::NpcGetDataResponse,
    npc::NpcNotifyData,
    ping::Ping,
    quest::QuestHistoryGetRequest,
    quest::QuestWorkGetRequest,
    robo::RoboGetListRequest,
    robo::RoboGetListResponse,
    robo::RoboGetObtainedSkillListRequest,
    robo::RoboGetObtainedSkillListResponse,
    robo::RoboVoiceTypeUpdateRequest,
    robo::RoboVoiceTypeUpdateResponse,
    version::VersionCheck,
    version::VersionCheckResponse,
    world::MapEnterRequest,
    world::MapEnterResponse,
    world::MapLinkGetDataRequest,
    world::MapLinkGetDataResponse,
    world::MapLinkNotifyData,
    world::WorldListRequest,
    world::WorldListResponse,
    world::WorldSelectRequest,
    world::WorldSelectResponse,
}
